# Generated by Django 2.0.2 on 2018-02-07 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogask', '0003_auto_20180206_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogask.Question'),
            preserve_default=False,
        ),
    ]
